default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: your_password

development:
  <<: *default
  database: wise_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: wise_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: wise_production
  host: localhost
  port: 5432
